src/account/urls.py
from django.urls import path
from .views import dashboard

app_name = 'account'
urlpatterns = [
    # login logout and register
    path('login-register', dashboard.LoginOrRegister.as_view(), name='login_register'),
    path('logout', dashboard.logout, name='logout'),
    # confirm account
    path('confirm/phonenumber', dashboard.ConfirmPhonenumber.as_view(), name='confirm_phonenumber'),
    path('confirm/phonenumber/check', dashboard.ConfirmPhonenumberCheckCode.as_view(),
         name='confirm_phonenumber_check_code'),
    # reset password
    path('reset-password', dashboard.reset_password, name='reset_password'),
    path('reset-password/send-code', dashboard.reset_password_send, name='reset_password_send_code'),
    path('reset-password/check-code', dashboard.reset_password_check, name='reset_password_check_code'),
    path('reset-password/set', dashboard.reset_password_set, name='reset_password_set'),

    # dashboard
    path('dashboard', dashboard.Dashboard.as_view(), name='dashboard'),
    path('dashboard/info/detail', dashboard.DashboardInfoDetail.as_view(), name='info_detail'),
    path('dashboard/info/change-password', dashboard.DashboardInfoChangePassword.as_view(),
         name='info_change_password'),
    # dashboard operations
    # --- user
    path('dashboard/user/<int:user_id>/permission/group/set', dashboard.UserPermissionGroupSet.as_view(),
         name='user_permission_group_set'),
    path('dashboard/user/update/password', dashboard.UserUpdatePassword.as_view(), name='user_update_password'),
    path('dashboard/user/update', dashboard.UserUpdate.as_view(), name='user_update'),
    path('dashboard/user/add', dashboard.UserAdd.as_view(), name='user_add'),
    path('dashboard/user/list', dashboard.UserList.as_view(), name='user_list'),
    path('dashboard/user/list/export', dashboard.UserListExport.as_view(), name='user_list_export'),
    path('dashboard/user/list/component/search', dashboard.UserListComponentPartial.as_view(),
         name='user_list_component_search'),

    path('dashboard/user/permissions/group/manage', dashboard.PermissionGroupsManage.as_view(),
         name='permission_groups_manage'),

    path('dashboard/user/permissions/group/add', dashboard.PermissionGroupsAdd.as_view(),
         name='permission_group_add'),

    path('dashboard/user/permissions/group/<int:group_id>/update', dashboard.PermissionGroupUpdate.as_view(),
         name='permission_group_update'),

    path('dashboard/user/permissions/group/<int:group_id>/delete', dashboard.PermissionGroupDelete.as_view(),
         name='permission_group_delete'),

    path('dashboard/user/<int:user_id>/detail', dashboard.UserDetail.as_view(), name='user_detail'),
    path('dashboard/user/<int:user_id>/detail/delete', dashboard.UserDetailDelete.as_view(), name='user_detail_delete'),
    path('dashboard/user/<int:user_id>/detail/update/admin', dashboard.UserDetailUpdateByAdmin.as_view(),
         name='user_detail_update_admin'),

    path('dashboard/user/<int:user_id>/building/available/set', dashboard.UserBuildingAvailableSet.as_view(),
         name='user_building_available_set'),
    path('dashboard/user/building/available/list', dashboard.UserBuildingAvailableList.as_view(),
         name='user_building_available_list'),
]

src/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('public.urls', namespace='public')),
    path('', include('receipt.urls', namespace='receipt')),
    path('', include('notification.urls', namespace='notification')),
    path('', include('support.urls', namespace='support')),
    path('u/', include('account.urls', namespace='account')),
    path('anything-except-admin/', admin.site.urls),
]

if settings.SERVE_FILE_BY_DJANGO:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler403 = 'public.views.err_403_handler'
handler404 = 'public.views.err_404_handler'
handler500 = 'public.views.err_500_handler'

src/notification/urls.py
from django.urls import path
from .views import dashboard

app_name = 'notification'
urlpatterns = [
    path('u/dashboard/notification/add', dashboard.NotificationAdd.as_view(), name='notification_dashboard_add'),
    path('u/dashboard/notification/list', dashboard.NotificationList.as_view(), name='notification_dashboard_list'),
    path('u/dashboard/notification/detail/<int:notification_id>', dashboard.NotificationDetail.as_view(), name='notification_dashboard_detail'),
    path('u/dashboard/notification/delete/<int:notification_id>', dashboard.NotificationDelete.as_view(), name='notification_dashboard_delete'),
    path('u/dashboard/notification/update/<int:notification_id>', dashboard.NotificationUpdate.as_view(), name='notification_dashboard_update'),

    path('u/dashboard/notification/building/add/', dashboard.NotificationBuildingAdd.as_view(), name='notification_building_dashboard_add'),

    path('u/dashboard/notification/user/add', dashboard.NotificationUserAdd.as_view(), name='notification_dashboard_user_add'),
    path('u/dashboard/notification/user/list', dashboard.NotificationUserList.as_view(), name='notification_dashboard_user_list'),
    path('u/dashboard/notification/user/detail/<int:notification_id>', dashboard.NotificationUserDetail.as_view(), name='notification_dashboard_user_detail'),

    path('u/dashboard/notification/user/personal/list', dashboard.NotificationUserPersonalList.as_view(), name='notification_dashboard_user_personal_list'),
]

src/notification/models.py
from django.utils.translation import gettext_lazy as _
from django.db import models
from django.urls import reverse
from django.contrib.auth import get_user_model
from django.utils.crypto import get_random_string
from jsonfield import JSONField
from core.models import BaseModel

User = get_user_model()


def upload_notification_src(instance, path):
    frmt = str(path).split('.')[-1]
    return f'images/notifications/{get_random_string(20)}.{frmt}'


class Notification(BaseModel):
    """
        notification in site
    """
    title = models.CharField(max_length=150)
    description = models.TextField(null=True, blank=True)
    image = models.ImageField(upload_to=upload_notification_src, null=True, blank=True, max_length=400)
    send_notify = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)

    class Meta:
        ordering = '-is_active', '-id'

    def __str__(self):
        return self.get_title()

    def get_title(self):
        return self.title or 'notification'

    def get_content(self):
        return f"""
            {self.get_title()}
            {self.description}
        """

    def get_absolute_url(self):
        return reverse('notification:notification_dashboard_detail', args=(self.id,))


class NotificationUser(BaseModel):
    """
        notification for user
    """
    type = models.CharField(max_length=100)
    title = models.CharField(max_length=150)
    description = models.TextField(null=True, blank=True)
    # attach content
    image = models.ImageField(upload_to=upload_notification_src, null=True, blank=True, max_length=400)
    kwargs = JSONField(null=True, blank=True)

    send_notify = models.BooleanField(default=True)
    to_user = models.ForeignKey(User, on_delete=models.CASCADE)
    # show for user or not
    is_showing = models.BooleanField(default=True)

    class Meta:
        ordering = '-id',
        permissions = (
            ('create_building_notification_user', _('Can create notification for users of building')),
        )

    def __str__(self):
        return f'notification for {self.to_user}'

    def get_title(self):
        return self.title or 'notification'

    def get_content(self):
        return f"""
            {self.get_title()}
            {self.description}
        """

    def get_absolute_url(self):
        return reverse('notification:notification_dashboard_user_detail', args=(self.id,))

    def get_link(self):
        try:
            return self.kwargs['link']
        except:
            return self.get_absolute_url()

    def get_image(self):
        try:
            return self.image.url
        except:
            return None

src/notification/forms.py
from django import forms
from . import models


class NotificationForm(forms.ModelForm):
    class Meta:
        model = models.Notification
        exclude = ('is_active',)


class NotificationUpdateForm(forms.ModelForm):
    class Meta:
        model = models.Notification
        fields = '__all__'


class NotificationUserForm(forms.ModelForm):
    class Meta:
        model = models.NotificationUser
        exclude = ('is_showing',)

src/notification/views/dashboard.py
from django.contrib import messages
from django.utils.translation import gettext_lazy as _
from django.contrib.auth import get_user_model
from django.shortcuts import get_object_or_404, Http404, redirect
from django.urls import reverse_lazy
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.views.generic import View, TemplateView, ListView

from receipt.models import Building

from core.mixins import views as core_mixins
from notification import forms, models

User = get_user_model()


class NotificationBuildingAdd(PermissionRequiredMixin, TemplateView):
    permission_required = ('notification.add_notificationuser', 'notification.create_building_notification_user')
    template_name = 'notification/dashboard/add-building-user.html'
    success_message = _('Notifications created successfully')

    def get_context_data(self, **kwargs):
        buildings = None
        user = self.request.user
        if user.is_superuser or user.has_perm('receipt.view_full_building'):
            buildings = Building.objects.filter(is_active=True)
        elif user.has_perm('receipt.view_admin_building'):
            buildings = user.get_available_buildings()
        elif user.has_perm('receipt.view_user_building'):
            buildings = models.Building.get_buildings_user(user)
        return {
            'buildings': buildings
        }

    def post(self, request):
        data = request.POST
        building_id = data.get('building')
        if not building_id:
            raise Http404
        building = get_object_or_404(Building, id=building_id)
        users = building.get_all_users()

        for user in users:
            data_notification = data.copy()
            data_notification['to_user'] = user
            data_notification['type'] = 'CUSTOM_NOTIFICATION'
            f = forms.NotificationUserForm(data=data_notification, files=request.FILES)
            if not f.is_valid():
                continue
            f.save()
        messages.success(request, self.success_message)
        return redirect('notification:notification_building_dashboard_add')


class NotificationAdd(PermissionRequiredMixin, core_mixins.CreateViewMixin, TemplateView):
    permission_required = ('notification.add_notification',)
    template_name = 'notification/dashboard/add.html'
    success_message = _('Notification created successfully')
    form = forms.NotificationForm


class NotificationList(PermissionRequiredMixin, ListView):
    permission_required = ('notification.view_notification',)
    template_name = 'notification/dashboard/list.html'
    paginate_by = 20
    queryset = models.Notification.objects.all()


class NotificationDetail(PermissionRequiredMixin, TemplateView):
    permission_required = ('notification.view_notification',)
    template_name = 'notification/dashboard/detail.html'

    def get_context_data(self, **kwargs):
        notification_id = kwargs.get('notification_id')
        notification = get_object_or_404(models.Notification, id=notification_id)
        context = {
            'notification': notification
        }
        return context


class NotificationDelete(PermissionRequiredMixin, core_mixins.DeleteViewMixin, TemplateView):
    permission_required = ('notification.delete_notification',)
    redirect_url = reverse_lazy('notification:notification_dashboard_list')

    def get_object(self, request, *args, **kwargs):
        notification_id = kwargs.get('notification_id')
        notification = get_object_or_404(models.Notification, id=notification_id)
        return notification


class NotificationUpdate(PermissionRequiredMixin, core_mixins.UpdateViewMixin, View):
    permission_required = ('notification.change_notification',)
    form = forms.NotificationUpdateForm

    def get_object(self):
        notification_id = self.kwargs.get('notification_id')
        return get_object_or_404(models.Notification, id=notification_id)


class NotificationUserAdd(PermissionRequiredMixin, core_mixins.CreateViewMixin, TemplateView):
    permission_required = ('notification.add_notificationuser',)
    template_name = 'notification/dashboard/add-user.html'
    success_message = _('Notification user created successfully')
    form = forms.NotificationUserForm

    def get_context_data(self, **kwargs):
        return {
            'users': User.objects.all()
        }

    def add_additional_data(self, data, obj=None):
        data['type'] = 'CUSTOM_NOTIFICATION'


class NotificationUserList(PermissionRequiredMixin, ListView):
    permission_required = ('notification.view_notificationuser',)
    template_name = 'notification/dashboard/list-user.html'
    paginate_by = 20
    queryset = models.NotificationUser.objects.all()


class NotificationUserPersonalList(ListView):
    template_name = 'notification/dashboard/personal-list.html'
    paginate_by = 20

    def get_queryset(self):
        return self.request.user.get_notifications()


class NotificationUserDetail(TemplateView):
    template_name = 'notification/dashboard/detail-user.html'

    def get_context_data(self, **kwargs):
        notification_id = kwargs.get('notification_id')
        notification = get_object_or_404(models.NotificationUser, id=notification_id)
        user = self.request.user
        # only own user and admin can access
        if notification.to_user != user and user.is_admin is False:
            raise Http404
        context = {
            'notification': notification
        }
        return context

src/notification/templates/notification/dashboard/add-user.html
{% extends 'account/dashboard/components/base/base_template.html' %}
{% load static %}
{% load render_partial %}

{% block Title %}
    افزودن اعلان برای کاربر
{% endblock %}


{% block Content %}
    {% include 'account/dashboard/components/base/nav.html' %}

    <section class="main_content dashboard_part large_header_bg">
        {% include 'account/dashboard/components/base/header.html' %}
        <div class="main_content_iner">
            <div class="container-fluid p-0 ">
                <div class="col-lg-12">
                    <div class="white_card mb_30">
                        <div class="white_card_header">
                            <div class="box_header m-0">
                                <div class="main-title">
                                    <h3 class="m-0">افزودن اعلان برای کاربر</h3>
                                </div>
                            </div>
                            <div class="breadcrumb">
                                <ul>
                                    <li>
                                        <a href="{% url 'account:dashboard' %}">داشبورد</a>
                                    </li>
                                    <li>
                                        <a href="#">اعلانات</a>
                                    </li>
                                    <li>
                                        <a href="">افزودن اعلان برای کاربر</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="white_card_body">
                            <div class="card-body">
                                <form action="{% url 'notification:notification_dashboard_user_add' %}" method="post"
                                      enctype="multipart/form-data">
                                    {% csrf_token %}
                                    <div class="row mb-3">
                                        <div class="col-md-6">
                                            <label class="form-label">
                                                عنوان
                                                <span class="field-required">*</span>
                                            </label>
                                            <input type="text" name="title" class="form-control"
                                                   placeholder="عنوان" minlength="2" maxlength="100" required>
                                        </div>
                                        <div class="col-md-6">
                                            <label class="form-label">
                                                عکس
                                            </label>
                                            <input type="file" name="image" class="form-control"
                                                   placeholder="عکس" accept="image/*">
                                        </div>
                                    </div>
                                    <div class="row mb-3">
                                        <div class="col-md-12">
                                            <label class="form-label">
                                                توضیحات
                                                <span class="field-required">*</span>
                                            </label>
                                            <textarea type="text" name="description" class="form-control" required
                                                      maxlength="400" minlength="2" placeholder="توضیحات"></textarea>
                                        </div>
                                    </div>
                                    <div class="row mb-3">
                                        <div class="col-md-12">
                                            <label class="form-label" for="sendNotifyNotification">
                                                ارسال اعلان
                                            </label>
                                            <div class="form-control d-flex justify-content-between align-center p-2">
                                                <label for="sendNotifyNotification">
                                                    <div>
                                                        ارسال اعلان از طریق پیامک و ایمیل به کاربر
                                                    </div>
                                                </label>
                                                <div class="px-2 mb-1">
                                                    <input type="checkbox" id="sendNotifyNotification" checked
                                                           class="form-check-input" name="send_notify"
                                                           style="transform: scale(1.3)">
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row mb-3">
                                        <div class="col-md-12">
                                            <label class="form-label" for="sendNotifyNotification">
                                                کاربر
                                            </label>
                                            <div class="form-control d-flex justify-content-between align-center p-2">
                                                <label for="btnSelectUserNotification">
                                                    <div class="input-select-label-name mt-1">
                                                        کاربر مورد نظر خود را انتخاب کنید
                                                    </div>
                                                </label>
                                                <div class="">
                                                    <input type="hidden" name="to_user" value="0">
                                                    <button class="btn btn-success font-80" selected="false"
                                                            type="button" data-bs-toggle="modal"
                                                            data-bs-target="#container-users"
                                                            id="btnSelectUserNotification">
                                                        انتخاب کاربر
                                                    </button>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="field field-button text-left">
                                        <button type="submit">ثبت</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% include 'account/dashboard/components/base/footer.html' %}
    </section>
    {% render_partial 'account.views.dashboard.UserListComponentPartial' %}
{% endblock %}


{% block Script %}
    <script>
        let input_select_user_component = document.querySelector('input[name="to_user"]')
        let input_select_user_component_name = document.querySelector('.input-select-label-name')
    </script>
    <script src="{% static 'scripts/user-list-component.js' %}"></script>
{% endblock %}

src/notification/templates/notification/dashboard/add.html
{% extends 'account/dashboard/components/base/base_template.html' %}

{% block Title %}
    افزودن اعلان عمومی
{% endblock %}


{% block Content %}
    {% include 'account/dashboard/components/base/nav.html' %}

    <section class="main_content dashboard_part large_header_bg">
        {% include 'account/dashboard/components/base/header.html' %}
        <div class="main_content_iner">
            <div class="container-fluid p-0 ">
                <div class="col-lg-12">
                    <div class="white_card mb_30">
                        <div class="white_card_header">
                            <div class="box_header m-0">
                                <div class="main-title">
                                    <h3 class="m-0">افزودن اعلان عمومی</h3>
                                </div>
                            </div>
                                <div class="breadcrumb">
                                <ul>
                                    <li>
                                        <a href="{% url 'account:dashboard' %}">داشبورد</a>
                                    </li>
                                    <li>
                                        <a href="#">اعلانات</a>
                                    </li>
                                    <li>
                                        <a href="">افزودن اعلان عمومی</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="white_card_body">
                            <div class="card-body">
                                <form action="{% url 'notification:notification_dashboard_add' %}" method="post"
                                      enctype="multipart/form-data">
                                    {% csrf_token %}
                                    <div class="row mb-3">
                                        <div class="col-md-6">
                                            <label class="form-label">
                                                عنوان
                                                <span class="field-required">*</span>
                                            </label>
                                            <input type="text" name="title" class="form-control"
                                                   placeholder="عنوان" minlength="2" maxlength="100" required>
                                        </div>
                                        <div class="col-md-6">
                                            <label class="form-label">
                                                عکس
                                            </label>
                                            <input type="file" name="image" class="form-control"
                                                   placeholder="عکس" accept="image/*">
                                        </div>
                                    </div>
                                    <div class="row mb-3">
                                        <div class="col-md-12">
                                            <label class="form-label">
                                                توضیحات
                                                <span class="field-required">*</span>
                                            </label>
                                            <textarea type="text" name="description" class="form-control" required
                                                      maxlength="400" minlength="2" placeholder="توضیحات"></textarea>
                                        </div>
                                    </div>
                                    <div class="row mb-3">
                                        <div class="col-md-12">
                                            <label class="form-label" for="sendNotifyNotification">
                                                ارسال اعلان
                                            </label>
                                            <div class="form-control d-flex justify-content-between align-center p-2">
                                                <label for="sendNotifyNotification">
                                                    <div>
                                                        ارسال اعلان از طریق پیامک و ایمیل به تمامی کاربران
                                                    </div>
                                                </label>
                                                <div class="px-2 mb-1">
                                                    <input type="checkbox" id="sendNotifyNotification"
                                                           class="form-check-input" name="send_notify" style="transform: scale(1.3)">
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="field field-button text-left">
                                        <button type="submit">ثبت</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% include 'account/dashboard/components/base/footer.html' %}
    </section>
{% endblock %}