src/account/urls.py
from django.urls import path
from .views import dashboard

app_name = 'account'
urlpatterns = [
    # login logout and register
    path('login-register', dashboard.LoginOrRegister.as_view(), name='login_register'),
    path('logout', dashboard.logout, name='logout'),
    # confirm account
    path('confirm/phonenumber', dashboard.ConfirmPhonenumber.as_view(), name='confirm_phonenumber'),
    path('confirm/phonenumber/check', dashboard.ConfirmPhonenumberCheckCode.as_view(),
         name='confirm_phonenumber_check_code'),
    # reset password
    path('reset-password', dashboard.reset_password, name='reset_password'),
    path('reset-password/send-code', dashboard.reset_password_send, name='reset_password_send_code'),
    path('reset-password/check-code', dashboard.reset_password_check, name='reset_password_check_code'),
    path('reset-password/set', dashboard.reset_password_set, name='reset_password_set'),

    # dashboard
    path('dashboard', dashboard.Dashboard.as_view(), name='dashboard'),
    path('dashboard/info/detail', dashboard.DashboardInfoDetail.as_view(), name='info_detail'),
    path('dashboard/info/change-password', dashboard.DashboardInfoChangePassword.as_view(),
         name='info_change_password'),
    # dashboard operations
    # --- user
    path('dashboard/user/<int:user_id>/permission/group/set', dashboard.UserPermissionGroupSet.as_view(),
         name='user_permission_group_set'),
    path('dashboard/user/update/password', dashboard.UserUpdatePassword.as_view(), name='user_update_password'),
    path('dashboard/user/update', dashboard.UserUpdate.as_view(), name='user_update'),
    path('dashboard/user/add', dashboard.UserAdd.as_view(), name='user_add'),
    path('dashboard/user/list', dashboard.UserList.as_view(), name='user_list'),
    path('dashboard/user/list/export', dashboard.UserListExport.as_view(), name='user_list_export'),
    path('dashboard/user/list/component/search', dashboard.UserListComponentPartial.as_view(),
         name='user_list_component_search'),

    path('dashboard/user/permissions/group/manage', dashboard.PermissionGroupsManage.as_view(),
         name='permission_groups_manage'),

    path('dashboard/user/permissions/group/add', dashboard.PermissionGroupsAdd.as_view(),
         name='permission_group_add'),

    path('dashboard/user/permissions/group/<int:group_id>/update', dashboard.PermissionGroupUpdate.as_view(),
         name='permission_group_update'),

    path('dashboard/user/permissions/group/<int:group_id>/delete', dashboard.PermissionGroupDelete.as_view(),
         name='permission_group_delete'),

    path('dashboard/user/<int:user_id>/detail', dashboard.UserDetail.as_view(), name='user_detail'),
    path('dashboard/user/<int:user_id>/detail/delete', dashboard.UserDetailDelete.as_view(), name='user_detail_delete'),
    path('dashboard/user/<int:user_id>/detail/update/admin', dashboard.UserDetailUpdateByAdmin.as_view(),
         name='user_detail_update_admin'),

    path('dashboard/user/<int:user_id>/building/available/set', dashboard.UserBuildingAvailableSet.as_view(),
         name='user_building_available_set'),
    path('dashboard/user/building/available/list', dashboard.UserBuildingAvailableList.as_view(),
         name='user_building_available_list'),
]

src/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('public.urls', namespace='public')),
    path('', include('receipt.urls', namespace='receipt')),
    path('', include('notification.urls', namespace='notification')),
    path('', include('support.urls', namespace='support')),
    path('u/', include('account.urls', namespace='account')),
    path('anything-except-admin/', admin.site.urls),
]

if settings.SERVE_FILE_BY_DJANGO:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler403 = 'public.views.err_403_handler'
handler404 = 'public.views.err_404_handler'
handler500 = 'public.views.err_500_handler'

src/receipt/urls.py
from django.urls import path
from .views import dashboard

app_name = 'receipt'
urlpatterns = [

    path('u/dashboard/project/add',dashboard.ProjectAdd.as_view(),name='project_dashboard_add'),
    path('u/dashboard/project/list',dashboard.ProjectList.as_view(),name='project_dashboard_list'),
    path('u/dashboard/project/<int:project_id>',dashboard.ProjectDetail.as_view(),name='project_dashboard_detail'),
    path('u/dashboard/project/<int:project_id>/update',dashboard.ProjectUpdate.as_view(),name='project_dashboard_detail_update'),
    path('u/dashboard/project/<int:project_id>/delete',dashboard.ProjectDelete.as_view(),name='project_dashboard_detail_delete'),


    path('u/dashboard/building/add', dashboard.BuildingAdd.as_view(), name='building_dashboard_add'),
    path('u/dashboard/building/list', dashboard.BuildingList.as_view(), name='building_dashboard_list'),
    path('u/dashboard/building/<int:building_id>', dashboard.BuildingDetail.as_view(),name='building_dashboard_detail'),
    path('u/dashboard/building/<int:building_id>/export', dashboard.BuildingDetailExport.as_view(),name='building_dashboard_detail_export'),
    path('u/dashboard/building/<int:building_id>/update', dashboard.BuildingDetailUpdate.as_view(),name='building_dashboard_detail_update'),
    path('u/dashboard/building/<int:building_id>/delete', dashboard.BuildingDetailDelete.as_view(),name='building_dashboard_detail_delete'),


    path('u/dashboard/receipt/add', dashboard.ReceiptAdd.as_view(), name='receipt_dashboard_add'),
    path('u/dashboard/receipt/list', dashboard.ReceiptList.as_view(), name='receipt_dashboard_list'),

    path('u/dashboard/receipt/<int:receipt_id>', dashboard.ReceiptDetail.as_view(), name='receipt_dashboard_detail'),
    path('u/dashboard/receipt/<int:receipt_id>/update', dashboard.ReceiptDetailUpdate.as_view(), name='receipt_dashboard_detail_update'),
    path('u/dashboard/receipt/<int:receipt_id>/accept', dashboard.ReceiptDetailAccept.as_view(), name='receipt_dashboard_detail_accept'),
    path('u/dashboard/receipt/<int:receipt_id>/reject', dashboard.ReceiptDetailReject.as_view(), name='receipt_dashboard_detail_reject'),
    path('u/dashboard/receipt/<int:receipt_id>/delete', dashboard.ReceiptDetailDelete.as_view(), name='receipt_dashboard_detail_delete'),

    path('u/dashboard/receipt/task/list', dashboard.ReceiptTaskList.as_view(), name='receipt_dashboard_task_list'),
    path('u/dashboard/receipt/task/<int:receipt_task_id>', dashboard.ReceiptTaskDetail.as_view(), name='receipt_dashboard_task_detail'),
    path('u/dashboard/receipt/task/<int:receipt_task_id>/accept', dashboard.ReceiptTaskDetailAccept.as_view(), name='receipt_dashboard_task_detail_accept'),
    path('u/dashboard/receipt/task/<int:receipt_task_id>/reject', dashboard.ReceiptTaskDetailReject.as_view(), name='receipt_dashboard_task_detail_reject'),
]

src/account/views/dashboard.py
import json
from django.utils.translation import gettext_lazy as _
from django.http import (JsonResponse, HttpResponseBadRequest, Http404, HttpResponse, HttpResponseRedirect)
from django.contrib import messages
from django.urls import reverse_lazy
from django.conf import settings
from django.db.models import Value, Q
from django.db.models.functions import Concat
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from django.views.generic import View, TemplateView, ListView
from django.contrib.auth.models import Group
from django.core import serializers
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import models as permission_models
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.auth import authenticate, login, get_user_model, logout as logout_handler
from core.auth.mixins import LoginRequiredMixinCustom
from core.auth.utils import get_available_permissions
from core.utils import add_prefix_phonenum, random_num, form_validate_err, get_media_url, log_event
from core import redis_py
from core.mixins import views as core_mixins
from receipt.models import Building, BuildingAvailable, Receipt, ReceiptTask
from notification.models import NotificationUser
from account import forms, exports

User = get_user_model()
RESET_PASSWORD_CONFIG = settings.RESET_PASSWORD_CONFIG
CONFIRM_PHONENUMBER_CONFIG = settings.CONFIRM_PHONENUMBER_CONFIG


class LoginOrRegister(TemplateView):
    template_name = 'account/login-register.html'

    def login_perform(self, data):
        request = self.request
        phonenumber = data.get('phonenumber', None)
        password = data.get('password', None)
        if not (phonenumber or password):
            messages.error(request, _('Please enter fields correctly'))
            return redirect('account:login_register')
        phonenumber = add_prefix_phonenum(phonenumber)
        user = authenticate(request, username=phonenumber, password=password)
        if user is None:
            messages.error(request, _('User not found or account is inactive'))
            return redirect('account:login_register')
        if user.is_active is False:
            messages.error(request, _('Account is inactive'))
            return redirect('account:login_register')
        login(request, user)
        messages.success(request, _('Welcome'))
        # redirect to url or dashboard
        next_url = request.GET.get('next')
        try:
            # maybe next url not valid
            if next_url:
                return redirect(next_url)
        except Exception as e:
            pass
        return redirect('account:dashboard')

    def register_perform(self, data):
        request = self.request
        f = forms.RegisterUserForm(data=data)
        if f.is_valid() is False:
            messages.error(request, _('Please enter fields correctly'))
            return redirect('account:login_register')
        # check for exists user
        phonenumber = f.cleaned_data['phonenumber']
        first_name = f.cleaned_data['first_name']
        last_name = f.cleaned_data['last_name']
        email = f.cleaned_data['email']
        if User.objects.filter(phonenumber=phonenumber).exists() or User.objects.filter(email=email).exists():
            messages.error(request, _('A user has already registered with this number'))
            return redirect('account:login_register')

        # create user
        password = f.cleaned_data['password2']
        user = User(
            phonenumber=phonenumber,
            email=email,
            first_name=first_name,
            last_name=last_name,
            # user must check and active by admin
            is_active=False
        )
        user.set_password(password)
        user.save()
        # add user group
        try:
            common_user_group = Group.objects.get(name='common_user_group_default')
            user.groups.add(common_user_group)
        except Group.DoesNotExist:
            pass
        messages.success(request,
                         _('Your account has been successfully created and will be activated after confirming your mobile number and checking your account'))
        return redirect('account:confirm_phonenumber')

    def post(self, request, *args, **kwargs):
        data = request.POST
        type_page = data.get('type-page', 'login')
        if type_page == 'login':
            return self.login_perform(data)
        elif type_page == 'register':
            return self.register_perform(data)


def logout(request):
    logout_handler(request)
    return redirect('public:home')


def reset_password(request):
    return render(request, 'account/reset-password.html')


@require_POST
def reset_password_send(request):
    # AJAX view
    data = json.loads(request.body)
    phonenumber = data.get('phonenumber', None)
    # validate data
    if not phonenumber:
        return HttpResponseBadRequest()
    # check user is exists
    try:
        phonenumber = add_prefix_phonenum(phonenumber)
        user = User.objects.get(phonenumber=phonenumber)
    except:
        raise Http404
    code = random_num(RESET_PASSWORD_CONFIG['CODE_LENGTH'])
    key = RESET_PASSWORD_CONFIG['STORE_BY'].format(phonenumber)
    # check code state set
    if redis_py.get_value(key) is not None:
        # code is already set
        return HttpResponse(status=409)
    # set code
    redis_py.set_value_expire(key, code, RESET_PASSWORD_CONFIG['TIMEOUT'])
    # send code
    NotificationUser.objects.create(
        type='RESET_PASSWORD_CODE_SENT',
        kwargs={
            'code': code
        },
        to_user=user,
        title=_('Reset password'),
        send_notify=True
    )
    return JsonResponse({})


@require_POST
def reset_password_check(request):
    # AJAX view
    data = json.loads(request.body)
    phonenumber = data.get('phonenumber', None)
    code = data.get('code', None)
    # validate data
    if (not code) or (not phonenumber):
        return HttpResponseBadRequest()
    phonenumber = add_prefix_phonenum(phonenumber)
    key = RESET_PASSWORD_CONFIG['STORE_BY'].format(phonenumber)
    # check code
    code_stored = redis_py.get_value(key)
    if code_stored is None:
        # code is not seted or timeout
        return HttpResponse(status=410)
    if code_stored != code:
        # code is wrong(not same)
        return HttpResponse(status=409)
    return JsonResponse({})


@require_POST
def reset_password_set(request):
    # AJAX view
    data = json.loads(request.body)
    f = forms.ResetPasswordSetForm(data)
    # validate data
    if f.is_valid() is False:
        return HttpResponseBadRequest()
    clean_data = f.cleaned_data
    # phonenumber must get from data (not clean_data)
    phonenumber = data['phonenumber']
    code = clean_data['code']
    password = clean_data['password2']
    # check user is exists
    try:
        phonenumber = add_prefix_phonenum(phonenumber)
        user = User.objects.get(phonenumber=phonenumber)
    except:
        raise Http404
    key = RESET_PASSWORD_CONFIG['STORE_BY'].format(phonenumber)
    # check code
    code_stored = redis_py.get_value(key)
    if code_stored is None:
        # code is not seted or timeout
        return HttpResponse(status=410)
    if code_stored != code:
        # code is wrong(not same)
        return HttpResponse(status=409)
    user.set_password(password)
    user.save()
    redis_py.remove_key(key)
    NotificationUser.objects.create(
        type='PASSWORD_CHANGED_SUCCESSFULLY',
        to_user=user,
        title=_('Your password changed successfully'),
    )
    return JsonResponse({})


class Dashboard(LoginRequiredMixinCustom, View):

    def get_context_common_user(self, request, user):
        buildings = Building.get_buildings_user(user)
        # chart data
        building_names = []
        building_payments = []

        for building in buildings:
            building_names.append(building.name)
            building_payments.append(building.get_building_payments_user(user))

        context = {
            'buildings': buildings,
            # chart data
            'building_names': json.dumps(building_names),
            'building_payments': json.dumps(building_payments),
        }
        return context

    def get_context_admin_user(self, request, user):
        buildings = user.get_available_buildings()
        # chart data
        building_names = []
        building_payments = []

        for building in buildings:
            building_names.append(building.name)
            building_payments.append(building.get_payments())

        if user.has_perm('account.view_full_user'):
            users = User.objects.get_users()
        else:
            users = User.objects.get_users().filter(
                buildingavailable__buildings__in=user.get_available_buildings()).distinct()
        context = {
            'buildings': buildings,
            'receipts': Receipt.objects.filter(building__in=buildings),
            'users': users,
            # chart data
            'building_names': json.dumps(building_names),
            'building_payments': json.dumps(building_payments),
        }
        return context

    def get_context_super_user(self, request, user):
        buildings = Building.objects.all()
        # chart data
        building_names = []
        building_payments = []

        for building in buildings:
            building_names.append(building.name)
            building_payments.append(building.get_payments())
        context = {
            'buildings': buildings,
            'receipts': Receipt.objects.all(),
            'users': User.common_user.all(),
            'admins': User.admin_user.all(),
            # chart data
            'building_names': json.dumps(building_names),
            'building_payments': json.dumps(building_payments),
        }
        return context

src/receipt/templates/receipt/dashboard/building/add.html
{% extends 'account/dashboard/components/base/base_template.html' %}

{% block Title %}
    اضافه کردن ساختمان
{% endblock %}


{% block Content %}
    {% include 'account/dashboard/components/base/nav.html' %}

    <section class="main_content dashboard_part large_header_bg">
        {% include 'account/dashboard/components/base/header.html' %}
        <div class="main_content_iner">
            <div class="container-fluid p-0 ">
                <div class="col-lg-12">
                    <div class="white_card mb_30">
                        <div class="white_card_header">
                            <div class="box_header m-0">
                                <div class="main-title">
                                    <h3 class="m-0">اضافه کردن ساختمان</h3>
                                </div>
                            </div>
                            <div class="breadcrumb">
                                <ul>
                                    <li>
                                        <a href="{% url 'account:dashboard' %}">داشبورد</a>
                                    </li>
                                    <li>
                                        <a href="{% url 'receipt:building_dashboard_list' %}">ساختمان ها</a>
                                    </li>
                                    <li>
                                        <a href="">افزودن ساختمان</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="white_card_body">
                            <div class="card-body">
                                <form action="{% url 'receipt:building_dashboard_add' %}" method="post">
                                    {% csrf_token %}
                                    <div class="row mb-3">
                                        <div class="col-md-6">
                                            <label class="form-label" for="inputNameBuilding">
                                                نام
                                                <span class="field-required">*</span>
                                            </label>
                                            <input type="text" name="name" class="form-control"
                                                   id="inputNameBuilding"
                                                   placeholder="نام" minlength="2" maxlength="100" required>
                                        </div>
                                        <div class="col-md-6">
                                            <label class="form-label" for="inputAddressBuilding">
                                                ادرس
                                                <span class="field-required">*</span>
                                            </label>
                                            <input type="text" name="address" class="form-control"
                                                   id="inputAddressBuilding" placeholder="ادرس"
                                                   minlength="3" maxlength="300" required>
                                        </div>
                                    </div>
                                    <div class="row mb-3">
                                        <div class="col-12">
                                            <label class="form-label" for="inputAddressBuilding">
                                                پروژه
                                                <span class="field-required">*</span>
                                            </label>
                                            <select name="project" required class="form-control form-select">
                                                {% for project in projects %}
                                                    <option value="{{ project.id }}">{{ project.name }}</option>
                                                {% endfor %}
                                            </select>
                                        </div>
                                    </div>
                                    <div class="row mb-3">
                                        <div class="col-md-12">
                                            <label class="form-label" for="inputDescriptionBuilding">
                                                توضیحات
                                            </label>
                                            <textarea type="text" name="description" class="form-control"
                                                      id="inputDescriptionBuilding"
                                                      placeholder="توضیحات" minlength="2" maxlength="400"></textarea>
                                        </div>
                                    </div>
                                    <div class="field field-button text-left">
                                        <button type="submit">ثبت</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% include 'account/dashboard/components/base/footer.html' %}
    </section>
{% endblock %}

src/receipt/templates/receipt/dashboard/building/list.html
{% extends 'account/dashboard/components/base/base_template.html' %}

{% block Title %}
    لیست ساختمان ها
{% endblock %}


{% block Content %}
    {% include 'account/dashboard/components/base/nav.html' %}

    <section class="main_content dashboard_part large_header_bg">
        {% include 'account/dashboard/components/base/header.html' %}
        <div class="main_content_iner">
            <div class="container-fluid p-0 ">
                <div class="col-lg-12">
                    <div class="white_card mb_30">
                        <div class="white_card_header">
                            <div class="box_header m-0">
                                <div class="main-title">
                                    <h3 class="m-0">لیست ساختمان ها</h3>
                                </div>
                            </div>
                            <div class="breadcrumb">
                                <ul>
                                    <li>
                                        <a href="{% url 'account:dashboard' %}">داشبورد</a>
                                    </li>
                                    <li>
                                        <a >پروژه</a>
                                    </li>
                                    <li>
                                        <a href="">ساختمان ها</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="white_card_body">
                            <div class="card-body">

                                <div class="list-row">
                                    <div class="title-list-row">
                                        <div class="col-2">
                                            نام
                                        </div>
                                        <div class="col-3">
                                            ادرس
                                        </div>
                                        <div class="col-2">
                                            توضیحات
                                        </div>
                                        <div class="col-2">
                                            درصد پیشرفت
                                        </div>
                                        <div class="col-2">
                                            وضعیت
                                        </div>
                                    </div>
                                    {% for building in object_list %}
                                        <div class="detail-row">
                                            <div class="col-2">
                                                <a href="{{ building.get_absolute_url }}">
                                                    {{ building.get_name_by_flag|truncatechars:30 }}
                                                </a>
                                            </div>
                                            <div class="col-3">
                                                {{ building.address|truncatechars:30 }}
                                            </div>
                                            <div class="col-2">
                                                {{ building.description|default:'بدون توضیحات'|truncatechars:20 }}
                                            </div>
                                            <div class="col-2">
                                                {{ building.progress_percentage }}
                                                <i class="fa fa-percentage icon-percentage-badge"
                                                   percentage-label="{{ building.progress_percentage_label }}"></i>
                                            </div>
                                            <div class="col-2">
                                                {% if building.is_active %}
                                                    فعال
                                                    <i class="fa fa-check-circle font-size-10 text-success"></i>
                                                {% else %}
                                                    غیر فعال
                                                    <i class="fa fa-minus-circle font-size-10 text-danger"></i>
                                                {% endif %}
                                            </div>
                                        </div>
                                    {% empty %}
                                        <div class="container-not-found-base">
                                            <p>ساختمانی یافت نشد</p>
                                        </div>
                                    {% endfor %}
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% include 'account/dashboard/components/base/footer.html' %}
    </section>
{% endblock %}