src/account/urls.py
from django.urls import path
from .views import dashboard

app_name = 'account'
urlpatterns = [
    # login logout and register
    path('login-register', dashboard.LoginOrRegister.as_view(), name='login_register'),
    path('logout', dashboard.logout, name='logout'),
    # confirm account
    path('confirm/phonenumber', dashboard.ConfirmPhonenumber.as_view(), name='confirm_phonenumber'),
    path('confirm/phonenumber/check', dashboard.ConfirmPhonenumberCheckCode.as_view(),
         name='confirm_phonenumber_check_code'),
    # reset password
    path('reset-password', dashboard.reset_password, name='reset_password'),
    path('reset-password/send-code', dashboard.reset_password_send, name='reset_password_send_code'),
    path('reset-password/check-code', dashboard.reset_password_check, name='reset_password_check_code'),
    path('reset-password/set', dashboard.reset_password_set, name='reset_password_set'),

    # dashboard
    path('dashboard', dashboard.Dashboard.as_view(), name='dashboard'),
    path('dashboard/info/detail', dashboard.DashboardInfoDetail.as_view(), name='info_detail'),
    path('dashboard/info/change-password', dashboard.DashboardInfoChangePassword.as_view(),
         name='info_change_password'),
    # dashboard operations
    # --- user
    path('dashboard/user/<int:user_id>/permission/group/set', dashboard.UserPermissionGroupSet.as_view(),
         name='user_permission_group_set'),
    path('dashboard/user/update/password', dashboard.UserUpdatePassword.as_view(), name='user_update_password'),
    path('dashboard/user/update', dashboard.UserUpdate.as_view(), name='user_update'),
    path('dashboard/user/add', dashboard.UserAdd.as_view(), name='user_add'),
    path('dashboard/user/list', dashboard.UserList.as_view(), name='user_list'),
    path('dashboard/user/list/export', dashboard.UserListExport.as_view(), name='user_list_export'),
    path('dashboard/user/list/component/search', dashboard.UserListComponentPartial.as_view(),
         name='user_list_component_search'),

    path('dashboard/user/permissions/group/manage', dashboard.PermissionGroupsManage.as_view(),
         name='permission_groups_manage'),

    path('dashboard/user/permissions/group/add', dashboard.PermissionGroupsAdd.as_view(),
         name='permission_group_add'),

    path('dashboard/user/permissions/group/<int:group_id>/update', dashboard.PermissionGroupUpdate.as_view(),
         name='permission_group_update'),

    path('dashboard/user/permissions/group/<int:group_id>/delete', dashboard.PermissionGroupDelete.as_view(),
         name='permission_group_delete'),

    path('dashboard/user/<int:user_id>/detail', dashboard.UserDetail.as_view(), name='user_detail'),
    path('dashboard/user/<int:user_id>/detail/delete', dashboard.UserDetailDelete.as_view(), name='user_detail_delete'),
    path('dashboard/user/<int:user_id>/detail/update/admin', dashboard.UserDetailUpdateByAdmin.as_view(),
         name='user_detail_update_admin'),

    path('dashboard/user/<int:user_id>/building/available/set', dashboard.UserBuildingAvailableSet.as_view(),
         name='user_building_available_set'),
    path('dashboard/user/building/available/list', dashboard.UserBuildingAvailableList.as_view(),
         name='user_building_available_list'),
]

src/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('public.urls', namespace='public')),
    path('', include('receipt.urls', namespace='receipt')),
    path('', include('notification.urls', namespace='notification')),
    path('', include('support.urls', namespace='support')),
    path('u/', include('account.urls', namespace='account')),
    path('anything-except-admin/', admin.site.urls),
]

if settings.SERVE_FILE_BY_DJANGO:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler403 = 'public.views.err_403_handler'
handler404 = 'public.views.err_404_handler'
handler500 = 'public.views.err_500_handler'

src/receipt/urls.py
from django.urls import path
from .views import dashboard

app_name = 'receipt'
urlpatterns = [

    path('u/dashboard/project/add',dashboard.ProjectAdd.as_view(),name='project_dashboard_add'),
    path('u/dashboard/project/list',dashboard.ProjectList.as_view(),name='project_dashboard_list'),
    path('u/dashboard/project/<int:project_id>',dashboard.ProjectDetail.as_view(),name='project_dashboard_detail'),
    path('u/dashboard/project/<int:project_id>/update',dashboard.ProjectUpdate.as_view(),name='project_dashboard_detail_update'),
    path('u/dashboard/project/<int:project_id>/delete',dashboard.ProjectDelete.as_view(),name='project_dashboard_detail_delete'),


    path('u/dashboard/building/add', dashboard.BuildingAdd.as_view(), name='building_dashboard_add'),
    path('u/dashboard/building/list', dashboard.BuildingList.as_view(), name='building_dashboard_list'),
    path('u/dashboard/building/<int:building_id>', dashboard.BuildingDetail.as_view(),name='building_dashboard_detail'),
    path('u/dashboard/building/<int:building_id>/export', dashboard.BuildingDetailExport.as_view(),name='building_dashboard_detail_export'),
    path('u/dashboard/building/<int:building_id>/update', dashboard.BuildingDetailUpdate.as_view(),name='building_dashboard_detail_update'),
    path('u/dashboard/building/<int:building_id>/delete', dashboard.BuildingDetailDelete.as_view(),name='building_dashboard_detail_delete'),


    path('u/dashboard/receipt/add', dashboard.ReceiptAdd.as_view(), name='receipt_dashboard_add'),
    path('u/dashboard/receipt/list', dashboard.ReceiptList.as_view(), name='receipt_dashboard_list'),

    path('u/dashboard/receipt/<int:receipt_id>', dashboard.ReceiptDetail.as_view(), name='receipt_dashboard_detail'),
    path('u/dashboard/receipt/<int:receipt_id>/update', dashboard.ReceiptDetailUpdate.as_view(), name='receipt_dashboard_detail_update'),
    path('u/dashboard/receipt/<int:receipt_id>/accept', dashboard.ReceiptDetailAccept.as_view(), name='receipt_dashboard_detail_accept'),
    path('u/dashboard/receipt/<int:receipt_id>/reject', dashboard.ReceiptDetailReject.as_view(), name='receipt_dashboard_detail_reject'),
    path('u/dashboard/receipt/<int:receipt_id>/delete', dashboard.ReceiptDetailDelete.as_view(), name='receipt_dashboard_detail_delete'),

    path('u/dashboard/receipt/task/list', dashboard.ReceiptTaskList.as_view(), name='receipt_dashboard_task_list'),
    path('u/dashboard/receipt/task/<int:receipt_task_id>', dashboard.ReceiptTaskDetail.as_view(), name='receipt_dashboard_task_detail'),
    path('u/dashboard/receipt/task/<int:receipt_task_id>/accept', dashboard.ReceiptTaskDetailAccept.as_view(), name='receipt_dashboard_task_detail_accept'),
    path('u/dashboard/receipt/task/<int:receipt_task_id>/reject', dashboard.ReceiptTaskDetailReject.as_view(), name='receipt_dashboard_task_detail_reject'),
]

src/receipt/views/dashboard.py
import json
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.db.models import Q, Value, Case, When
from django.db.models.functions import Concat
from django.utils.translation import gettext_lazy as _
from django.core.exceptions import PermissionDenied
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.views.generic import View, TemplateView, ListView
from django.http import Http404
from core.auth.mixins import LoginRequiredMixinCustom
from core.mixins import views as core_mixins
from core.utils import form_validate_err, get_media_url, create_form_messages
from receipt import forms, models, exports


class ProjectAdd(LoginRequiredMixinCustom, PermissionRequiredMixin, core_mixins.CreateViewMixin, TemplateView):
    permission_required = ('receipt.add_project',)
    template_name = 'receipt/dashboard/project/add.html'
    form = forms.ProjectAddForm


class ProjectList(LoginRequiredMixinCustom, PermissionRequiredMixin, core_mixins.PermissionObjectsMixin, ListView):
    permission_required = ('receipt.view_project',)
    template_name = 'receipt/dashboard/project/list.html'

    def get_qs_permission(self, *args, **kwargs):
        return {
            'receipt.view_full_project': {
                'name': 'projects',
                'queryset': models.Project.objects.all().distinct()
            },
            'receipt.view_project': {
                'name': 'projects',
                'queryset': models.Project.objects.filter(
                    building__in=self.request.user.get_available_buildings()).distinct()
            },
        }

    def get_queryset(self):
        return self.get_context_perm()['projects']


class ProjectDetail(LoginRequiredMixinCustom, PermissionRequiredMixin, core_mixins.PermissionObjectsMixin,
                    TemplateView):
    permission_required = ('receipt.view_project',)
    template_name = 'receipt/dashboard/project/detail.html'

    def get_qs_permission(self, *args, **kwargs):
        project = kwargs.get('project')
        return {
            'receipt.view_full_building': {
                'name': 'buildings',
                'queryset': project.get_buildings()
            },
            'receipt.view_building': {
                'name': 'buildings',
                'queryset': project.get_buildings().filter(pk__in=self.request.user.get_available_building_ids())
            },
        }

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        project_id = kwargs.get('project_id')
        project = get_object_or_404(models.Project, id=project_id)

        context['project'] = project
        context.update(self.get_context_perm(project=project))
        return context


class ProjectUpdate(LoginRequiredMixinCustom, PermissionRequiredMixin, core_mixins.UpdateViewMixin, View):
    permission_required = ('receipt.change_project',)
    form = forms.ProjectUpdateForm

    def get_object(self):
        project_id = self.kwargs.get('project_id')
        return get_object_or_404(models.Project, id=project_id)


class ProjectDelete(LoginRequiredMixinCustom, PermissionRequiredMixin, core_mixins.DeleteViewMixin, View):
    permission_required = ('receipt.delete_project',)

    def get_object(self, request, *args, **kwargs):
        project_id = kwargs.get('project_id')
        return get_object_or_404(models.Project, id=project_id)


class BuildingAdd(LoginRequiredMixinCustom, PermissionRequiredMixin, core_mixins.CreateViewMixin, TemplateView):
    permission_required = ('receipt.add_building',)
    template_name = 'receipt/dashboard/building/add.html'
    form = forms.BuildingAddForm

    def get_context_data(self, **kwargs):
        context = {
            'projects': models.Project.objects.all()
        }
        return context


class BuildingList(LoginRequiredMixinCustom, PermissionRequiredMixin, core_mixins.PermissionObjectsMixin, ListView):
    permission_required = ('receipt.view_building',)
    template_name = 'receipt/dashboard/building/list.html'

    def get_qs_permission(self, *args, **kwargs):
        user = self.request.user
        return {
            'receipt.view_full_building': {
                'name': 'buildings',
                'queryset': models.Building.objects.all()
            },
            'receipt.view_admin_building': {
                'name': 'buildings',
                'queryset': user.get_available_buildings()
            },
            'receipt.view_user_building': {
                'name': 'buildings',
                'queryset': models.Building.get_buildings_user(user)
            },
        }

    def get_queryset(self):
        return self.get_context_perm().get('buildings', [])


class BuildingDetail(LoginRequiredMixinCustom, PermissionRequiredMixin, TemplateView):
    permission_required = ('receipt.view_building',)
    template_name = 'receipt/dashboard/building/detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        building_id = self.kwargs.get('building_id')
        building = self.get_building(building_id)
        # chart data
        user_names = []
        user_payments = []
        for user in building.get_users():
            user_names.append(user.get_full_name())
            user_payments.append(building.get_building_payments_user(user))

        context.update({
            'building': building,
            'projects': models.Project.objects.all(),
            # chart data
            'user_names': json.dumps(user_names),
            'user_payments': json.dumps(user_payments)
        })
        return context

    def get_building(self, building_id):
        user = self.request.user
        building = get_object_or_404(models.Building, id=building_id)
        if not user.has_perm('receipt.view_full_building'):
            if not (building in user.get_available_buildings()):
                raise Http404
        return building


class BuildingDetailExport(LoginRequiredMixinCustom, PermissionRequiredMixin, View):
    permission_required = ('receipt.export_building',)

    def get(self, request, building_id):
        building = get_object_or_404(models.Building, id=building_id)
        excel_file = exports.Excel.perform_export_building(building)
        excel_file = get_media_url(excel_file)
        return HttpResponseRedirect(excel_file)


class BuildingDetailUpdate(LoginRequiredMixinCustom, PermissionRequiredMixin, core_mixins.UpdateViewMixin, View):
    permission_required = ('receipt.change_building',)
    form = forms.BuildingUpdateForm

    def get_object(self):
        building_id = self.kwargs.get('building_id')
        return get_object_or_404(models.Building, id=building_id)


class BuildingDetailDelete(LoginRequiredMixinCustom, PermissionRequiredMixin, core_mixins.DeleteViewMixin, View):
    permission_required = ('receipt.delete_building',)

    def get_object(self, request, *args, **kwargs):
        building_id = kwargs.get('building_id')
        return get_object_or_404(models.Building, id=building_id)


class ReceiptAdd(LoginRequiredMixinCustom, PermissionRequiredMixin, core_mixins.CreateViewMixin,
                 core_mixins.TransactionAtomicViewMixin, TemplateView):
    permission_required = ('receipt.add_receipt',)
    template_name = 'receipt/dashboard/receipt/add.html'
    form = forms.ReceiptAddForm

    def get_context_data(self, **kwargs):
        context = {
            'buildings': self.get_buildings_by_user_perm()
        }
        return context

    def get_buildings_by_user_perm(self):
        user = self.request.user
        if user.has_perm('receipt.view_full_building'):
            return models.Building.objects.filter(is_active=True)
        available_buildings = user.get_available_buildings()
        return models.Building.objects.filter(is_active=True, pk__in=available_buildings)

    def add_additional_data(self, data, obj=None):
        user = self.request.user
        data.setdefault('user', user)

        # check and set status
        data['status'] = 'pending'
        if user.has_perm('receipt.auto_accept_receipt'):
            data['status'] = 'accepted'

    def do_success(self):
        user = self.request.user
        if not user.is_common_admin:
            return
        if user.has_perm('receipt.auto_accept_receipt'):
            return
        # create receipt task admin
        form_data = self.get_data()
        form_data.update({
            'receipt': self.obj,
            'user_admin': self.request.user,
            'receipt_status': 'accepted',
        })
        # set status accept if user has auto accept task perm
        if user.has_perm('receipt.auto_accept_receipt_task'):
            form_data['status'] = 'accepted'
        form_receipt_task = forms.ReceiptTaskAddForm(form_data, self.request.FILES)
        if not form_receipt_task.is_valid():
            create_form_messages(self.request, form_receipt_task)
            self.obj.delete()
        form_receipt_task.save()


class ReceiptList(LoginRequiredMixinCustom, PermissionRequiredMixin, core_mixins.PermissionObjectsMixin, ListView):
    permission_required = ('receipt.view_receipt',)
    template_name = 'receipt/dashboard/receipt/list.html'
    paginate_by = 20

    def sort(self, objects):
        sort_by = self.request.GET.get('sort_by', 'need_to_check')
        if sort_by == 'latest':
            objects = objects.order_by('-id')
        elif sort_by == 'oldest':
            objects = objects.order_by('id')
        elif sort_by == 'highest_amount':
            objects = objects.order_by('-amount')
        elif sort_by == 'lowset_amount':
            objects = objects.order_by('amount')
        elif sort_by == 'need_to_check':
            objects = objects.order_by(Case(
                When(status="pending", then=Value(1)),

src/receipt/templates/receipt/dashboard/receipt/task/common_admin/list.html
{% extends 'account/dashboard/components/base/base_template.html' %}

{% block Title %}
    لیست رسید های مشاهده شده و یا ثبت شده
{% endblock %}


{% block Content %}
    {% include 'account/dashboard/components/base/nav.html' %}

    <section class="main_content dashboard_part large_header_bg">
        {% include 'account/dashboard/components/base/header.html' %}
        <div class="main_content_iner">
            <div class="container-fluid p-0 ">
                <div class="col-lg-12">
                    <div class="white_card mb_30">
                        <div class="white_card_header">
                            <div class="box_header m-0">
                                <div class="main-title">
                                    <h3 class="m-0"> لیست رسید های مشاهده شده و یا ثبت شده</h3>
                                </div>
                            </div>
                            <div class="breadcrumb">
                                <ul>
                                    <li>
                                        <a href="{% url 'account:dashboard' %}">داشبورد</a>
                                    </li>
                                    <li>
                                        <a href="">  لیست رسید های مشاهده شده و یا ثبت شده</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div>
                            <div class="filters-radio">
                                <div class="title">
                                    مرتب بر اساس :
                                </div>
                                <div class="container">
                                    <div>
                                        <a class="{% if not request.GET.sort_by or request.GET.sort_by == 'latest' %}active{% endif %}"
                                           href="{% url 'receipt:receipt_dashboard_task_list' %}?sort_by=latest&search={{ request.GET.search }}">
                                            جدید ترین
                                        </a>
                                    </div>
                                    <div>
                                        <a class="{% if request.GET.sort_by == 'oldest' %}active{% endif %}"
                                           href="{% url 'receipt:receipt_dashboard_task_list' %}?sort_by=oldest&search={{ request.GET.search }}">
                                            قدیمی ترین
                                        </a>
                                    </div>
                                    <div>
                                        <a class="{% if request.GET.sort_by == 'need_to_check' %}active{% endif %}"
                                           href="{% url 'receipt:receipt_dashboard_task_list' %}?sort_by=need_to_check&search={{ request.GET.search }}">
                                            نیاز به بررسی
                                        </a>
                                    </div>
                                    <div>
                                        <a class="{% if request.GET.sort_by == 'highest_amount' %}active{% endif %}"
                                           href="{% url 'receipt:receipt_dashboard_task_list' %}?sort_by=highest_amount&search={{ request.GET.search }}">
                                            بیشترین مبلغ
                                        </a>
                                    </div>
                                    <div>
                                        <a class="{% if request.GET.sort_by == 'lowset_amount' %}active{% endif %}"
                                           href="{% url 'receipt:receipt_dashboard_task_list' %}?sort_by=lowset_amount&search={{ request.GET.search }}">
                                            کمترین مبلغ
                                        </a>
                                    </div>
                                </div>
                            </div>
                            <div>
                                <form action="{% url 'receipt:receipt_dashboard_task_list' %}">
                                    <input type="hidden" name="sort_by" value="{{ request.GET.sort_by }}">
                                    <p class="title">جست و جو :</p>
                                    <div class="cnt-search col-11 col-md-7">
                                        <input type="text" name="search"
                                               placeholder="نام ساختمان ، مبلغ ، کد رهگیری و .."
                                               value="{{ request.GET.search }}">
                                        <div>
                                            {% if request.GET.search %}
                                                <a class="text-danger font-80" style="margin-left: 8px;"
                                                   href="{% url 'receipt:receipt_dashboard_task_list' %}">
                                                    <i class="fa fa-times"></i>
                                                </a>
                                            {% endif %}
                                            <button>
                                                <i class="fa fa-search"></i>
                                            </button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                        <div class="white_card_body">
                            <div class="card-body">
                                <div class="list-row">
                                    <div class="title-list-row">
                                        <div class="col-2">
                                            نام ساختمان
                                        </div>
                                        <div class="col-2">
                                            رسید
                                        </div>
                                        <div class="col-2">
                                            مبلغ
                                        </div>
                                        <div class="col-2">
                                            وضعیت
                                        </div>
                                        <div class="col-2">
                                            جزئیات
                                        </div>
                                    </div>
                                    {% for receipt_task in object_list %}
                                        <div class="detail-row">
                                            <div class="col-2">
                                                <a href="{{ receipt_task.receipt.building.get_absolute_url }}">
                                                    {{ receipt_task.receipt.building.name|truncatechars:30 }}
                                                </a>
                                            </div>
                                            <div class="col-2">
                                                <a href="{{ receipt_task.receipt.get_absolute_url }}">
                                                    {{ receipt_task.receipt.tracking_code }}
                                                </a>
                                            </div>
                                            <div class="col-2">
                                                <span class="price-el">{{ receipt_task.receipt.amount }}</span>
                                            </div>
                                            <div class="col-2">
                                                {% if receipt_task.status == 'accepted' %}
                                                    بررسی شده
                                                    <i class="fa fa-check-circle font-size-10 text-success"></i>
                                                {% elif receipt_task.status == 'rejected' %}
                                                    رد شده
                                                    <i class="fa fa-times-circle font-size-10 text-danger"></i>
                                                {% else %}
                                                    نیاز به بررسی
                                                    <i class="fa fa-exclamation-triangle font-size-10 text-warning"></i>
                                                {% endif %}
                                            </div>
                                            <div class="col-2">
                                                <a href="{{ receipt_task.get_absolute_url }}">
                                                    مشاهده
                                                    <i class="far fa-arrow-alt-circle-left"></i>
                                                </a>
                                            </div>
                                        </div>
                                    {% empty %}
                                        <div class="container-not-found-base">
                                            <p>رسیدی یافت نشد</p>
                                            {% if request.GET.sort_by or request.GET.search %}
                                                <a href="{% url 'receipt:receipt_dashboard_task_list' %}"
                                                   class="font-80 mt-2 d-block text-warning">
                                                    <i class="fa fa-times"></i>
                                                    حذف فیلتر و جست و جو
                                                </a>
                                            {% endif %}
                                        </div>
                                    {% endfor %}
                                </div>
                                <div class="pagination">
                                    <div class="step-links">
                                        {% if page_obj.has_previous %}
                                            <span class="pagination-previous">
                                                <a href="?page=1">اول</a><a
                                                    href="?page={{ page_obj.previous_page_number }}">قبلی</a>
                                            </span>
                                        {% endif %}
                                        <span class="current">
                                        صفحه  {{ page_obj.number }} از {{ page_obj.paginator.num_pages }}
                                        </span>

                                        {% if page_obj.has_next %}
                                            <span class="pagination-next">
                                                <a href="?page={{ page_obj.next_page_number }}">بعدی</a><a
                                                    href="?page={{ page_obj.paginator.num_pages }}">اخر</a>
                                            </span>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% include 'account/dashboard/components/base/footer.html' %}
    </section>
{% endblock %}